# 日志器配置
# in_use 里列出的才会被 run.py 实例化；往里面加 'wandb' 即可启用 wandb。
in_use: [csv]

csv:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${hydra:runtime.cwd}/outputs/${exp_name}
  name: 'logs'
  version: null

tensorboard:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${hydra:runtime.cwd}/outputs/${exp_name}
  name: 'tb'

wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: ${hydra:runtime.cwd}/outputs/${exp_name}
  project: 'quu-s-instance-level-pose'
  name: ${exp_name}
  offline: false
